{% set version = "1.5.0" %}

package:
  name: freezegun
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/freezegun/freezegun-{{ version }}.tar.gz
  sha256: 200a64359b363aa3653d8aac289584078386c7c3da77339d257e46a01fb5c77c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.7

test:
  imports:
    - freezegun
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/spulec/freezegun
  license: Apache-2.0
  license_file: LICENSE
  summary: Let your Python tests travel through time

extra:
  recipe-maintainers:
    - ocefpaf
