{% set version = "1.3.1" %}

package:
  name: freezegun
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/freezegun/freezegun-{{ version }}.tar.gz
  sha256: 48984397b3b58ef5dfc645d6a304b0060f612bcecfdaaf45ce8aff0077a6cb6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - python-dateutil >=2.7

test:
  imports:
    - freezegun
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/spulec/freezegun
  license: Apache-2.0
  license_file: LICENSE
  summary: Let your Python tests travel through time

extra:
  recipe-maintainers:
    - ocefpaf
